x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow.Dockerfile
  environment: &airflow-common-env
    AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 60
    AIRFLOW__API_AUTH__JWT_SECRET: ${FERNET_KEY}
    AIRFLOW__API_AUTH__JWT_ISSUER: "qmj-airflow"
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW_UID: 50000
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
    _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USER}
    _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
    AIRFLOW_CONN_MY_TRINO_CONN: '${TRINO_CONNECTION}'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__PARALLELISM: 4
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 4
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 30
    AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
    _AIRFLOW_DB_MIGRATE: 'true'
    _AIRFLOW_WWW_USER_CREATE: 'true'
    AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE: 'false'
    PYTHONPATH: /opt/airflow/app
    MINIO_USER: ${MINIO_USER}
    MINIO_PASSWORD: ${MINIO_PASSWORD}
    AIRFLOW_CONN_PLATFORM_DB: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  volumes:
    - ./orchestration/dags:/opt/airflow/dags:ro
    - ./orchestration/logs:/opt/airflow/logs
    - ./orchestration/plugins:/opt/airflow/plugins
    - ./orchestration/config:/opt/airflow/config
    - ./transform:/opt/airflow/transform
    - .:/opt/airflow/app:ro
    - ./web_ui:/opt/airflow/app/web_ui:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - monitoring_net
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy

x-nessie-env: &nessie-shared-env
  nessie.version.store.type: JDBC
  nessie.version.store.persist.jdbc.datasource: postgresql
  nessie.version.store.persist.jdbc.schema: nessie
  quarkus.datasource.postgresql.jdbc.url: jdbc:postgresql://postgres:5432/platform_db?currentSchema=nessie
  quarkus.datasource.postgresql.username: ${POSTGRES_USER}
  quarkus.datasource.postgresql.password: ${POSTGRES_PASSWORD}
  nessie.catalog.default-warehouse: miniolakehouse
  nessie.catalog.warehouses.miniolakehouse.location: s3://financial-data-lake/
  nessie.catalog.service.s3.default-options.endpoint: http://minio:9000
  nessie.catalog.service.s3.default-options.path-style-access: 'true'
  nessie.catalog.service.s3.default-options.region: us-east-1
  nessie.catalog.service.s3.default-options.access-key: urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
  nessie.catalog.secrets.access-key.name: ${MINIO_USER}
  nessie.catalog.secrets.access-key.secret: ${MINIO_PASSWORD}

services:
  airflow-apiserver:
    <<: *airflow-common
    container_name: airflow-apiserver
    command: api-server
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - monitoring_net
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: unless-stopped
    networks:
      - monitoring_net
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - monitoring_net
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
  airflow-cli:
    <<: *airflow-common
    profiles: [ "tools" ]
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    depends_on:
      <<: *airflow-common-depends-on
    networks:
      - monitoring_net
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      <<: *airflow-common-depends-on
    entrypoint: /bin/bash
    user: root
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
          export AIRFLOW_UID=$$(id -u)
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required."
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended."
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo
        fi

        echo
        echo "Airflow version:"
        /entrypoint airflow version

        echo
        echo "Installing dbt dependencies into the 'transform' directory..."
        echo
        cd /opt/airflow/transform && /opt/airflow/dbt_venv/bin/dbt deps
        echo "Successfully installed dbt dependencies!"

        # ĐÃ XÓA TOÀN BỘ LỆNH MKDIR VÀ CHOWN ĐỔI QUYỀN SỞ HỮU!
        echo
        echo "Airflow Init hoàn tất an toàn, trả lại quyền kiểm soát cho Host!"

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "shared_preload_libraries=pg_partman_bgw" ]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres_database/init_postgres_db:/docker-entrypoint-initdb.d
    networks:
      - monitoring_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 5s
    mem_limit: 512m

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 5
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    networks:
      - monitoring_net

    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    mem_limit: 2048m
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:v1.5.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - monitoring_net
    volumes:
      - ./infra_config/config_docker/ui_kafba.yaml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - kafka

  grafana:
    image: grafana/grafana:13.1.0-24697775169
    container_name: grafana
    networks:
      - monitoring_net
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra_config/config_docker/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - plugins-trino:/var/lib/grafana/plugins/trino
  loki:
    image: grafana/loki:3.7.1
    container_name: loki
    networks:
      - monitoring_net
    ports:
      - "3100:3100"
    restart: unless-stopped
    env_file:
      - .env
    command: -config.file=/etc/loki/local-config.yaml -config.expand-env=true
    volumes:
      - ./infra_config/config_docker/loki_config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    depends_on:
      create-buckets:
        condition: service_completed_successfully

  minio:
    image: quay.io/minio/aistor/minio:RELEASE.2026-04-14T21-32-45Z
    container_name: aistor-server
    networks:
      - monitoring_net
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./minio.license:/minio.license
      - minio_data:/mnt/data
    command: server /mnt/data --console-address ":9001" --license /minio.license

  create-buckets:
    image: minio/mc:latest
    restart: on-failure
    networks:
      - monitoring_net
    env_file:
      - .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " echo 'Đang chờ MinIO khởi động...';  until (/usr/bin/mc alias set myminio http://minio:9000 $${MINIO_USER} $${MINIO_PASSWORD});  do
        sleep 1;
      done;   /usr/bin/mc mb --ignore-existing myminio/loki-data;   /usr/bin/mc mb --ignore-existing myminio/loki-ruler;   echo 'hoàn thành tạo bucket';   exit 0; "

  dev-container:
    build: .
    container_name: dev-container
    command: [ "sleep", "infinity" ]
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - monitoring_net

  nessie:
    image: ghcr.io/projectnessie/nessie:0.107.4
    container_name: nessie
    user: root
    ports:
      - "19120:19120"
    restart: unless-stopped
    environment:
      <<: *nessie-shared-env
    volumes:
      - nessie_data:/var/lib/nessie/data
    depends_on:
      - minio
    networks:
      - monitoring_net

  nessie-cli:
    image: ghcr.io/projectnessie/nessie-cli:0.107.4
    container_name: nessie_cli_tool
    profiles: [ "tools" ]
    stdin_open: true
    tty: true
    networks:
      - monitoring_net
    depends_on:
      - nessie

  nessie-gc:
    image: ghcr.io/projectnessie/nessie-gc:0.107.4
    container_name: nessie_gc_tool
    profiles: [ "tools" ]
    networks:
      - monitoring_net
    environment:
      - AWS_REGION=us-east-1

  nessie-admin:
    image: ghcr.io/projectnessie/nessie-server-admin:0.107.4
    container_name: nessie_admin_tool
    profiles: [ "tools" ]
    networks:
      - monitoring_net
    depends_on:
      - nessie
    environment:
      <<: *nessie-shared-env

  trino:
    image: trinodb/trino:480
    container_name: trino
    ports:
      - "9090:8080"
    restart: unless-stopped
    networks:
      - monitoring_net
    volumes:
      - ./trino_etc:/etc/trino
    depends_on:
      - minio
      - nessie
    mem_limit: 6gb

  vector:
    image: timberio/vector:0.55.0-alpine
    container_name: vector
    ports:
      - "5001:5000"
    user: root
    restart: unless-stopped
    networks:
      - monitoring_net
    command: [ "--config", "/etc/vector/vector.yaml", "--watch-config" ]
    volumes:
      - ./infra_config/config_docker/vector_config.yaml:/etc/vector/vector.yaml:ro
      - ./vector_log:/tmp/vector_log
      - vector_data:/var/lib/vector
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db_data:
  grafana_data:
  kafka_data:
  minio_data:
  promtail_data:
  nessie_data:
  trino:
  plugins-trino:
  loki_data:
  vector_data:


networks:
  monitoring_net:
    driver: bridge
