sources:
  trino_http_listener:
    type: http_server
    address: "0.0.0.0:5000"
    decoding:
      codec: json

transforms:
  trino_processed:
    type: remap
    inputs: ["trino_http_listener"]
    source: |-
      if !exists(.statistics) {
            abort
        }

      new_event= {}

      # basic information
      new_event.query_id = to_string(.metadata.queryId) ?? "unknown_id"
      new_event.user_name = to_string(.context.user) ?? "unknown_user"
      new_event.source_app = to_string(.context.source) ?? "unknown_app"
      new_event.catalog_name = to_string(.context.catalog) ?? "unknown_catalog"
      new_event.schema_name = to_string(.context.schema) ?? "unknown_schema"
      new_event.query_state = to_string(.metadata.queryState) ?? "UNKNOWN"
      new_event.created_at = to_string(.createTime) ?? "1970-01-01T00:00:00Z"

      
      # query text process
      raw_query = to_string(.metadata.query) ?? ""
      query_no_comment = replace(raw_query, r'/\*[\s\S]*?\*/', "")
      query_one_line = replace(query_no_comment, r'\s+', " ")
      new_event.query_text = strip_whitespace(query_one_line)

      

      # finops metrics
      new_event.cpu_time_s = to_float(.statistics.cpuTime) ?? 0.0
      new_event.failed_cpu_time_s = to_float(.statistics.failedCpuTime) ?? 0.0
      new_event.wall_time_s = to_float(.statistics.wallTime) ?? 0.0
      new_event.scanned_bytes = to_int(.statistics.physicalInputBytes) ?? 0
      new_event.peak_memory_bytes = to_int(.statistics.peakUserMemoryBytes) ?? 0
      . = new_event
      
sinks:
  # debug_only:
  #   type: file
  #   inputs: 
  #     - trino_processed
  #   # Tự động tạo file mới với tên chứa: Năm-Tháng-Ngày_Giờ-Phút-Giây
  #   path: /tmp/vector_log/trino_RAW_DATA_%Y-%m-%d_%H-%M-%S.json
  #   encoding:
  #     codec: json

  postgres_finops_output:
    type: postgres
    inputs: 
      - trino_processed
    endpoint: "postgresql://tkan:Tkan2005@postgres:5432/finance_db"
    table: "finops.trino_finops_logs"
    

    batch:
      max_events: 500      
      timeout_secs: 5      
    buffer:
      type: disk           
      max_size: 1073741824 
      when_full: block
