fundamental:
  source: ${MY_SOURCE}       
  url_template: https://restv2.${MY_SOURCE}.vn/symbols/{ticker}/fundamental
  table_name_postgres: "ingestion_metadata_fundamental"
  topic: 'fundamental'
  data_type: 'fundamental'
historical_quotes:
  source: ${MY_SOURCE}
  url_template: https://restv2.${MY_SOURCE}.vn/symbols/{ticker}/historical-quotes?startDate={start_date}&endDate={end_date}&offset={offset}&limit={limit}
  table_name_postgres: "ingestion_metadata_historical_quotes"
  topic: 'historical_quotes'
  data_type: 'historical_quotes'
  default_limit: 500
  default_offset: 0
  




    