event-listener.name=http
http-event-listener.log-created=false
http-event-listener.log-completed=true
http-event-listener.connect-ingest-uri=http://vector:5000
http-event-listener.connect-retry-count=3
http-event-listener.connect-retry-delay=5s
