name: transform
profile: transform

model-paths: ["models"]       # Code SQL xử lý data -> Vứt vào thư mục tên là 'models'
seed-paths: ["seeds"]         # File CSV nhỏ (từ điển) -> Vứt vào thư mục tên là 'seeds'
test-paths: ["tests"]         # Code kiểm tra lỗi -> Vứt vào thư mục tên là 'tests'
analysis-paths: ["analyses"]  # Code nháp -> Vứt vào thư mục tên là 'analyses'
macro-paths: ["macros"]       # Hàm tự viết -> Vứt vào thư mục tên là 'macros'
snapshot-paths: ["snapshots"] # Lưu lịch sử thay đổi -> Vứt vào thư mục tên là 'snapshots'


clean-targets: [target, logs, .user.yml]

models:
  transform:          
    +materialized: table
    bronze:
      +schema: bronze    
    staging:
      +schema: staging
    silver:
      +materialized: incremental
      +schema: silver
    gold:
      +schema: gold
      +materialized: table
  elementary:
    +materialized: table
    +database: ops_db
    +schema: elementary

data_tests:
  transform:
    +limit: 1000
    +store_failures: true
    +schema: test_results
    

flags:
  +require_certificate_validation: True
vars:
  'dbt_date:time_zone': 'Asia/Ho_Chi_Minh'
  days_back: 45 # The maximal timeframe for which the test will collect data.
  test_sample_row_count: 20 # number of failed test rows, which are stored in the table test_result_rows
  detection_period: # the period which is used to detect data quality issues
    period: day
    count: 10
  exclude_detection_period_from_training: true # exclude the detection period from training data, preventing from overlapping data quality issues with training data
  detection_delay: 
    period: day 
    count: 1
  # timestamp_column: loaded_at # set at silver layer level
  # where_expression: EXTRACT(DOW FROM timestamp_column) BETWEEN 2 AND 6 # set at silver layer level