transform:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: admin
      host: "{{ env_var('DBT_HOST', 'trino') }}"
      port: "{{ env_var('DBT_PORT', 8080) | int }}"
      catalog: lakehouse_main
      schema: bronze
      threads: 4
      timezone: Asia/Ho_Chi_Minh

      session_properties:
        join_distribution_type: BROADCAST
