transform: 
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: admin
      host: trino
      port: 8080
      database: lakehouse
      schema: bronze
      threads: 4
      timezone: Asia/Ho_Chi_Minh

      session_properties:
        join_distribution_type: BROADCAST

      
      
            


          