connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie-catalog.uri=http://nessie:19120/api/v2
iceberg.nessie-catalog.ref=dev
iceberg.nessie-catalog.default-warehouse-dir=s3://financial-data-lake/
fs.native-s3.enabled=true
s3.aws-access-key=YOUR_MINIO_ACCESS_KEY
s3.aws-secret-key=YOUR_MINIO_SECRET_KEY
s3.endpoint=http://minio:9000
s3.path-style-access=true
s3.region=us-east-1
iceberg.register-table-procedure.enabled=true