connector.name=postgresql
connection-url=jdbc:postgresql://postgres:5432/ops_db
connection-user=YOUR_POSTGRES_USER
connection-password=YOUR_POSTGRES_PASSWORD
metadata.cache-ttl=1m
metadata.cache-missing=true