name: GitHub Actions Demo

# LỖI 1: Biến môi trường không tồn tại. (Đúng phải là github.actor)
run-name: ${{ github.nguoi_dung_ao }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    # LỖI 2: Sai chính tả từ khóa. (Đúng phải là runs-on có chữ 's')
    run-on: ubuntu-latest
    
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - : Check out repository code
        uses: actions/checkout@v4
        with:
          # LỖI 3: Truyền tham số tào lao mà action checkout không hề có.
          tham_so_tao_lao: abcxyz
          
      - name: List files in the repository
        run: ls ${{ github.workspace }}
        
      # LỖI 4: Viết step mà quên mất lệnh "run:" hoặc "uses:"
      - name: In ra trang thai
        "🍏 This job's status is ${{ job.status }}."